[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.layer_enforcer]
modules = ["demo_layered"]
ignore = ["demo_layered.ignore"]
layers = "layers.yml"

